#! /bin/sh
### BEGIN INIT INFO
# Provides:        firstboot
# Required-Start:  $networking
# Required-Stop:   $networking
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: A script that runs once
# Description: A script that runs once
### END INIT INFO

sleep 10

### install snaps
snap install keepassxc
snap install docker
snap install firefox
snap install slack
snap install skype

# docker permissions
group add docker
groupadd docker
gpasswd -a mwind docker

### synology
cd /tmp
wget 'https://global.download.synology.com/download/Tools/CloudStationDrive/4.2.6-4408/Ubuntu/Installer/x86_64/synology-cloud-station-drive-4408.x86_64.deb'
dpkg -i synology-cloud-station-drive-4408.x86_64.deb

### vim config
cd /opt/
git clone https://github.com/mattwind/vim.git

# setup vim for root
cd /opt/vim/
/usr/bin/nohup /bin/bash setup.sh

# setup vim for user
su - mwind
cd /opt/vim/
/usr/bin/nohup /bin/bash setup.sh

### sudo user
/bin/bash -c 'echo "mwind ALL=(ALL) NOPASSWD: ALL" | (EDITOR="tee -a" visudo)'

# Remove our firstboot service so that it won't run again
update-rc.d firstboot remove

# Reboot into the updated system
/sbin/reboot
